before_script:
    - apt-get update -qq && apt-get install -y -qq libsdl1.2-dev libpng-dev libsdl-ttf2.0-dev libsdl-image1.2-dev liblua5.1-0-dev zip
    - apt-get install -y -qq libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev
    - apt-get install -y -qq gcc-mingw-w64-i686 g++-mingw-w64-i686 mingw-w64-tools nsis

stages:
    - build

job_linux:
    stage: build
    script:
        - "cd src && make && make ziprelease"
        - "API=sdl2 make && API=sdl2 make ziprelease"
    artifacts:
        paths:
            - "*.zip"
            - "grafx2*.tgz"

job_win32:
    stage: build
    script:
        - "WIN32CROSS=1 make 3rdparty"
        - "WIN32CROSS=1 make -j3"
        - "WIN32CROSS=1 make ziprelease"
        - "WIN32CROSS=1 make win32installer"
        - "WIN32CROSS=1 API=win32 make -j3"
        - "WIN32CROSS=1 API=win32 make ziprelease"
        - "WIN32CROSS=1 API=win32 make win32installer"
    artifacts:
        paths:
            - "*.zip"
            - "install/grafx2*.exe"
